name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose coverage python-coveralls
        pip install .
    - name: Analysing the code with pylint
      run: |
        nosetests pybiopax -v --with-coverage --cover-inclusive --cover-package=pybiopax
