name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose coverage python-coveralls
        pip install .
    - name: Run unit tests
      run: |
        nosetests pybiopax -v --with-coverage --cover-inclusive --cover-package=pybiopax
